cities/urls.py
from django.urls import path
from .views import (home, CityDetailView, CityCreateView,
                    CityUpdateView, CityDeleteView,
                    CityListView)
app_name='cities'

urlpatterns=[
    path('',CityListView.as_view(),name='home'),
    path('<int:pk>',CityDetailView.as_view(),name='detail'),
    path('add/',CityCreateView.as_view(),name='create'),
    path('update/<int:pk>/',CityUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',CityDeleteView.as_view(),name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    find_routes, home, add_routes, save_route, RouteListView, RouteDetailView,
    RouteDeleteView,
)
from .views import team

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('find_routes/', find_routes, name='find_routes'),
                  path('cities/', include('cities.urls')),
                  path('trains/', include('trains.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('add_routes/', add_routes, name='add_routes'),
                  path('save_route/', save_route, name='save_route'),
                  path('list/', RouteListView.as_view(), name='list'),
                  path('route/<int:pk>', RouteDetailView.as_view(), name='route_detail'),
                  path('route/<int:pk>/delete/', RouteDeleteView.as_view(), name='route_delete'),
                  path('team/', team, name='team'),
                  path('ckdeditor/', include('ckeditor_uploader.urls'))

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trains/urls.py
from django.urls import path
from .views import (home, TrainListView, TrainDetailView,
                    TrainUpdateView, TrainCreateView,
                    TrainDeleteView)

app_name='trains'

urlpatterns=[
    path('',TrainListView.as_view(),name='home'),
    path('<int:pk>',TrainDetailView.as_view(),name='detail'),
    path('add/',TrainCreateView.as_view(),name='create'),
    path('update/<int:pk>/',TrainUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',TrainDeleteView.as_view(),name='delete')
]

trains/models.py
from django.core.exceptions import ValidationError
from django.db import models

from cities.models import City


class Train(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Train name')
    travel_time = models.PositiveSmallIntegerField(verbose_name='Travel time')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='from_city_set')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='to_city_set')
    start_train_day = models.DateField(null=True, blank=True)
    start_train_time = models.TimeField(null=True, blank=True)
    end_train_day = models.DateField(null=True, blank=True)
    place = models.IntegerField(default=0)

    def __str__(self):
        return f'Train N{self.name} and city {self.from_city}'

    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError('Cities name must be diffirent !!!')
        qs = Train.objects.filter(name=self.name,
                                  from_city=self.from_city,
                                  to_city=self.to_city,
                                  start_train_day=self.start_train_day,
                                  start_train_time=self.start_train_time,
                                  end_train_day=self.end_train_day)
        if qs.exists():
            raise ValidationError("Information didn't change or this train exists!")

    def save(self, *args, **kwargs):
        self.clean()

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Train'
        verbose_name_plural = 'Trains'


class TrainTest(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Train number')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='from_shaxar')

trains/forms.py
from django import forms
from .models import Train
from cities.models import City


class TrainForm(forms.ModelForm):
    name = forms.CharField(label='Poyezd raqami',
                                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'misol: Bux123'}))
    travel_time=forms.IntegerField(label='Sayohat vaqti',
                                    widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'misol: 56'}))
    from_city=forms.ModelChoiceField(label='Qaysi shaxardan',empty_label='shaxar tanlang',
                                    queryset=City.objects.all(),
                                    widget=forms.Select(attrs={'class':'form-control'}))
    to_city = forms.ModelChoiceField(label='Qaysi shaxarga',empty_label='shaxar tanlang',
                                    queryset=City.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model=Train
        fields='__all__'

trains/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render, Http404, get_object_or_404
from django.urls import reverse_lazy
from .forms import TrainForm
from .models import Train
from django.views.generic import (DetailView, CreateView,
                                  UpdateView, DeleteView, ListView)


def home(request):
    qs=Train.objects.all()
    lst=Paginator(qs,2)
    page_number=request.GET.get('page')
    page_obj=lst.get_page(page_number)
    context={'page_obj':page_obj}
    return render(request,'trains/home.html',context)


class TrainListView(ListView):
    model=Train
    template_name='trains/home.html'
    paginate_by=5
    context_object_name='trains'

class TrainDetailView(DetailView):
    model=Train
    template_name = 'trains/detail.html'
    context_object_name = 'detail'

class TrainUpdateView(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model=Train
    template_name = 'trains/create.html'
    form_class = TrainForm
    success_url = reverse_lazy('trains:home')
    success_message='Poyezd malumotlari o`zgartrildi!'

class TrainCreateView(SuccessMessageMixin,LoginRequiredMixin,CreateView):
    model=Train
    template_name = 'trains/create.html'
    form_class = TrainForm
    success_url = reverse_lazy('trains:home')
    success_message = 'Poyezd yaratildi!'

class TrainDeleteView(SuccessMessageMixin,LoginRequiredMixin,DeleteView):
    model = Train
    template_name = 'trains/delete_city.html'
    success_url = reverse_lazy('trains:home')
    success_message = 'Poyezd o`chirildi!'

templates/trains/create.html
{% extends "base.html" %}

{% block content %}

{% if not form.instance.pk  %}
    <h2>Add train</h2>
{% else %}
    <h2>Edit train</h2>
{% endif %}
<div class="row">
    <div class="col-md-4">
        <form method="POST">{% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="saqlash" class="btn btn-primary btn-sm">
        </form>
    </div>
</div>
{% endblock content %}

templates/trains/delete_city.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <form method="POST">{% csrf_token %}
            Delete <b>{{object.name}}</b> train ?<br>
            <input type="submit" value="Submit" class="btn btn-danger btn-sm"> &nbsp; <a href="{% url 'cities:home' %}" class="btn btn-primary btn-sm">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/trains/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>Train information</h1>
<div class="row">
    <div class="col-md">
        <table class="table table-striped">
            <tr>
                <th>Train number</th>
                <th>From city</th>
                <th>To city</th>
                <th>Travel time</th>
            </tr>

             <tr>
                 <td>{{object.name}}</td>
                 <td>{{object.from_city}}</td>
                 <td>{{object.to_city}}</td>
                 <td>{{object.travel_time}} hours</td>
             </tr>

        </table>
    </div>
</div>

<!--detail page gorod-->
<div class="row">
    <div class="col-md-4">
        <a href="{% url 'trains:home' %}" class="btn btn-primary btn-sm">List of cities</a>
    </div>
</div>
</div>

{% endblock %}

templates/trains/home.html
{% extends 'base.html' %}

{% block content %}


<div class="row">
    <div class="col-md-8 mx-auto my-2">
        <h1>Trains</h1>
        <table class="table table-striped">
            <tr>
                <th>Train number</th>
                <th>From city</th>
                <th>To city</th>
                <th>Sayohat vaqti</th>
                {% if request.user.is_superuser %}
                <th>Update</th>
                <th>Delete</th>
                {%endif%}
            </tr>
        {% for object in page_obj %}
             <tr>
                 <td><a style="text-decoration:none" href="{% url 'trains:detail' object.pk %}">{{object.name}}</a></td>
                 <td>{{object.from_city}}</td>
                 <td>{{object.to_city}}</td>
                 <td>{{object.travel_time}} hours</td>
                  {% if request.user.is_superuser %}
                 <td><a href="{% url 'trains:update' object.pk %}" class="btn btn-primary btn-sm">Update</a></td>
                 <td><a href="{% url 'trains:delete' object.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
                 {%endif%}
             </tr>
        {% endfor %}
        </table>
    </div>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      <li class="page-item">
         {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% endif %}
    </li>
      {% for page in page_obj.paginator.page_range %}
            <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
      {% endfor %}
    <li class="page-item">
         {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% endif %}
    </li>
  </ul>
</nav>



{% endblock %}