cities/urls.py
from django.urls import path
from .views import (home, CityDetailView, CityCreateView,
                    CityUpdateView, CityDeleteView,
                    CityListView)
app_name='cities'

urlpatterns=[
    path('',CityListView.as_view(),name='home'),
    path('<int:pk>',CityDetailView.as_view(),name='detail'),
    path('add/',CityCreateView.as_view(),name='create'),
    path('update/<int:pk>/',CityUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',CityDeleteView.as_view(),name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    find_routes, home, add_routes, save_route, RouteListView, RouteDetailView,
    RouteDeleteView,
)
from .views import team

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('find_routes/', find_routes, name='find_routes'),
                  path('cities/', include('cities.urls')),
                  path('trains/', include('trains.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('add_routes/', add_routes, name='add_routes'),
                  path('save_route/', save_route, name='save_route'),
                  path('list/', RouteListView.as_view(), name='list'),
                  path('route/<int:pk>', RouteDetailView.as_view(), name='route_detail'),
                  path('route/<int:pk>/delete/', RouteDeleteView.as_view(), name='route_delete'),
                  path('team/', team, name='team'),
                  path('ckdeditor/', include('ckeditor_uploader.urls'))

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cities/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Shahar')
    info = models.CharField(max_length=1000)
    about_city = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='city_images')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "City"
        verbose_name_plural = "Cities"
        ordering = ["name"]

cities/forms.py
from django import forms

from .models import City
from ckeditor.widgets import CKEditorWidget
from django.utils.safestring import mark_safe

class CityForm(forms.ModelForm):
    name=forms.CharField(label='Shaxar nomi',
                         widget=forms.TextInput(
                         attrs={'class':'form-control','placeholder':'misol: Buxoro'}))
    about_city=forms.CharField(widget=CKEditorWidget())
    shahar_haqida_qisqa=forms.CharField(label=mark_safe('shaxar haiqda qisqa'))

    class Meta:
        model=City
        fields=('name','shahar_haqida_qisqa','about_city')

cities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (DetailView, CreateView,
                                  UpdateView, DeleteView, ListView)

from .forms import CityForm
from .models import City


def home(request):
    qs = City.objects.all()
    lst = Paginator(qs, 1)
    page_number = request.GET.get('page')
    page_obj = lst.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'cities/home.html', context)


class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'cities/detail.html'


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:home')
    success_message = 'Add new city!'


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = CityForm
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:home')
    success_message = 'Edited city info!'


class CityDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = City
    template_name = 'cities/delete_city.html'
    success_url = reverse_lazy('cities:home')
    success_message = 'Deleted city!'


class CityListView(ListView):
    model = City
    template_name = 'cities/home.html'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(CityListView, self).get_context_data(**kwargs)
        context['form'] = CityForm
        return context

templates/cities/create.html
{% extends "base.html" %}

{% block content %}
<div class="container">
{% if not form.instance.pk  %}
    <h2>Add city</h2>
{% else %}
    <h2>Edit city</h2>
{% endif %}
<div class="row">
    <div class="col-md-4">
        <form method="POST">{% csrf_token %}
            {{form.as_p}}
            {{form.media}}
            <input type="submit" value="Submit" class="btn btn-primary btn-sm">
        </form>
    </div>
</div>
    </div>
{% endblock content %}

templates/cities/delete_city.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <form method="POST">{% csrf_token %}
            Siz <b>{{object.name}} </b> delete?<br>
            <input type="submit" value="Submit" class="btn btn-danger btn-sm"> &nbsp; <a href="{% url 'cities:home' %}" class="btn btn-primary btn-sm">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/cities/detail.html
{% extends 'base.html' %}
{% block gif %}




{% endblock gif %}


{% block content %}

    <div class="container">
        <h1>About {{ city.name }} city</h1>
        <div class="row pb-0">
            <div class="col-md">
                <p>{{ city.about_city|safe }}</p>
            </div>

        </div>

        <!--detail page gorod-->
        <div class="row mb-3">
            <div class="col-md-4">
                <a href="{% url 'cities:home' %}" class="btn btn-primary btn-sm">List of Cities</a>
                <a href="{% url 'find_routes' %}" class="btn btn-outline-success btn-sm">Travel</a>
            </div>
        </div>

    </div>


{% endblock %}

templates/cities/home.html
{% extends 'base.html' %}

{% block content %}



<div class="container">
    <h1>List of cities</h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3" >
                  {% for city in page_obj %}
                      <div class="col mb-4">
                          <a href="{% url 'cities:detail' pk=city.id %}" class="text-decoration-none">
                        <div class="card">
                          <img src="{{city.image.url}}" class="card-img-top" alt="{{city.name}}" height="220">
                          <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'cities:detail' pk=city.id %}" class="text-decoration-none">{{city.name}}</a></h5>
                            <p class="card-text">{{city.shahar_haqida_qisqa|truncatechars:110}}</p>
                              {% if request.user.is_superuser %}
                                 <a  href="{% url 'cities:update' pk=city.id %}"><buttun type="submit" class="btn btn-primary btn-sm">update</buttun></a>
                                 <a href="{% url 'cities:delete' pk=city.id %}"><buttun type="submit" class="btn btn-danger btn-sm">delete</buttun></a>
                              {% endif %}
                          </div>
                        </div>
                        </div>
                  {% endfor %}
        </div>
</div>


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      <li class="page-item">
         {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        {% endif %}
    </li>
      {% for page in page_obj.paginator.page_range %}
            <li class="page-item {% if page == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{page}}">{{page}}</a>
            </li>
      {% endfor %}
    <li class="page-item">
         {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        {% endif %}
    </li>
  </ul>
</nav>



{% endblock %}