accounts/urls.py
from django.urls import path
from accounts.views import login_view,logout_view,register

app_name='accounts'

urlpatterns=[
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register,name='register')

]

cities/urls.py
from django.urls import path
from .views import (home, CityDetailView, CityCreateView,
                    CityUpdateView, CityDeleteView,
                    CityListView)
app_name='cities'

urlpatterns=[
    path('',CityListView.as_view(),name='home'),
    path('<int:pk>',CityDetailView.as_view(),name='detail'),
    path('add/',CityCreateView.as_view(),name='create'),
    path('update/<int:pk>/',CityUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',CityDeleteView.as_view(),name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from routes.views import (
    find_routes, home, add_routes, save_route, RouteListView, RouteDetailView,
    RouteDeleteView,
)
from .views import team

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('find_routes/', find_routes, name='find_routes'),
                  path('cities/', include('cities.urls')),
                  path('trains/', include('trains.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('add_routes/', add_routes, name='add_routes'),
                  path('save_route/', save_route, name='save_route'),
                  path('list/', RouteListView.as_view(), name='list'),
                  path('route/<int:pk>', RouteDetailView.as_view(), name='route_detail'),
                  path('route/<int:pk>/delete/', RouteDeleteView.as_view(), name='route_delete'),
                  path('team/', team, name='team'),
                  path('ckdeditor/', include('ckeditor_uploader.urls'))

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trains/urls.py
from django.urls import path
from .views import (home, TrainListView, TrainDetailView,
                    TrainUpdateView, TrainCreateView,
                    TrainDeleteView)

app_name='trains'

urlpatterns=[
    path('',TrainListView.as_view(),name='home'),
    path('<int:pk>',TrainDetailView.as_view(),name='detail'),
    path('add/',TrainCreateView.as_view(),name='create'),
    path('update/<int:pk>/',TrainUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',TrainDeleteView.as_view(),name='delete')
]

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'cities:create' as trains_create_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as routes_list_url %}
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>

    {% block gif %}
    {% endblock gif %}

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

     <link rel="stylesheet" href="{% static 'css/jobs.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <title>TravelUz</title>
</head>
<body class="gif">


<nav class="navbar navbar-expand-lg navbar-light container fixed-top" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"><img style="width:30px;height:25px;margin-bottom:5px; border-radius: 50%;" src="{% static 'img/train1.png' %}" alt="">TravelUz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"  id="navbarNavDropdown">
      <ul class="navbar-nav" style="margin-left:auto;">
        <li class="nav-item">
          <a class="nav-link {% if request.path == cities_home_url %}active{% endif %}" aria-current="page" href="{% url 'cities:home'%}">City</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == trains_home_url %}active{% endif %}" href="{% url 'trains:home' %}">Train</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == routes_list_url %}active{% endif %}" href="{% url 'list' %}">My Travel</a>
        </li>
          {% if request.user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
            Add
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'cities:create' %}">Add city</a></li>
            <li><a class="dropdown-item" href="{% url 'trains:create' %}">Add train</a></li>
          </ul>
        </li>
          {% endif %}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{% url 'team' %}">Bizning jamoa</a>#}
{#            </li>#}
          {% if request.user.is_authenticated %}
             <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i> {{request.user}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'list' %}">My Travel</a></li>
              <div class="dropdown-divider"></div>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a></li>
          </ul>
        </li>
          {% else %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a>
            </li>
          {% endif %}


      </ul>

    </div>
  </div>
</nav>
<div class="container" style="margin-top:50px">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
                {% if messages %}
                        {% for message in messages %}
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                     <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{ message }}
                                         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                {% else %}
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                {% endif %}
                        {% endfor %}
                {% endif %}
        </div>
    </div>
</div>

{% block content %}{% endblock %}

<!-- Site footer -->

<!--<button style="height:50px;width:60px" class="btn btn-danger brn-sm" onclick="myFunction()"><i class="fa fa-moon-o" aria-hidden="true"></i></button>-->

</body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>

        $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
        });
    </script>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>hello world django junior {{User}}!</h1>
<p>django coder</p>

{% endblock %}

templates/home1.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block gif %}
<link rel="stylesheet" href="{% static 'css/gif.css' %}">
{% endblock gif %}
{% block content %}
{% load static %}

<div class="row">
    <h3 style="margin-left:450px"><i class="fa fa-train" aria-hidden="true"></i> Lets Travel!</h3>
    <div class="col-md-4" style="margin-left:450px">

        <form method="POST" action="{% url 'find_routes' %}" style="margin-bottom:25px;">{% csrf_token %}
              {{form.as_p}}
            <input type="submit" value="qidiruv" class="btn btn-primary btn-sm">
        </form>
    </div>
</div>
{% endblock content %}

templates/team.html
{% extends 'base.html' %}

{% block title %} Team {% endblock title %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

{% block content %}

<!-- Team -->

<section id="team" style="">
    <h5 class="section-title h2"><i>travel.uz </i>jamoasi</h5>
    <div class="container">
        <div class="row" style="padding-left:220px">
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="image-flip" >
                    <div class="mainflip flip-0">
                        <div class="frontside">
                            <div class="card shadow">
                                <div class="card-body text-center">
                                    <p><img class=" img-fluid" src="https://sunlimetech.com/portfolio/boot4menu/assets/imgs/team/img_02.png" alt="card image"></p>
                                    <h4 class="card-title">Bekzod Xudayberdiyev</h4>
                                    <p class="card-text">Python,Django developer.</p>
                                    <a href="" ><i class="fas fa-code"></i></a>

                                </div>
                            </div>
                        </div>
                        <div class="backside">
                            <div class="card shadow">
                                <div class="card-body text-center mt-4">
                                    <h4 class="card-title">Haqida</h4>
                                    <p class="card-text">Tug'ilgan joy: Samarqand viloyati<br>yoshim 21 da,hozirda TATU 3-kurs talabasi.</p>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <a class="social-icon text-xs-center" target="_blank" href="https://t.me/bxudayberdiyev">
                                                <i class="fab fa-telegram"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="https://github.com/XudayberdiyevB" class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fab fa-github"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="https://bekzodcv.netlify.app/"><i class="fas fa-globe"></i></a>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./Team member -->
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                    <div class="mainflip">
                        <div class="frontside">
                            <div class="card shadow" >
                                <div class="card-body text-center">
                                    <p><img class=" img-fluid" src="https://avatars.githubusercontent.com/u/69134199?v=4" alt="card image"></p>
                                    <h4 class="card-title">Shaxzod To'lisov</h4>
                                    <p class="card-text">Backend developer</p>
                                    <a href="" ><i class="fas fa-code"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="backside">
                            <div class="card">
                                <div class="card-body text-center mt-4">
                                    <h4 class="card-title">Haqida</h4>
                                    <p class="card-text">Tug'ilgan joy: Buxoro viloyati,yoshim 21 da,hozirda TATU 3-kurs talabasi.
                                        <br><br>Men dasturchi bo`lish uchun har qanday to`siqlarni yengib o`tishga tayyorman</p>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <a href="https://twitter.com/Shaxzad99" class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fab fa-twitter"></i>
                                            </a>
                                        </li>

                                        <li class="list-inline-item">
                                            <a href="https://t.me/Shaxzad99" class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fab fa-telegram"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="https://github.com/ShaxaDev" class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fab fa-github"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a href="https://shaxzod.netlify.app/" class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fa fa-globe"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./Team member -->

        </div>
    </div>
</section>
<!-- Team -->

{% endblock content %}